    name: Deploy MultiDocker
    on:
      push:
        branches:
          - main # check your repo, your default branch might be master!
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t darpan/react-test -f ./client/Dockerfile.dev ./client
          - run: docker run -e CI=true darpan/react-test npm test
     
          - run: docker build -t darpan/multi-client-28-01 ./client
          - run: docker build -t darpan/multi-nginx-28-01 ./nginx
          - run: docker build -t darpan/multi-server-28-01 ./server
          - run: docker build -t darpan/multi-worker-28-01 ./worker
     
          - run: docker push darpan/multi-client-28-01
          - run: docker push darpan/multi-nginx-28-01
          - run: docker push darpan/multi-server-28-01
          - run: docker push darpan/multi-worker-28-01
     
          - name: Generate deployment package
            run: zip -r deploy.zip . -x '*.git*'
     
         